### ISSUE TITLE
NullPointerException when getting ocsp certificate from signature

### ISSUE THREAD

**Issue by BertaHarsing** [open-eid/digidoc4j#33]
I am trying to get ocsp certificate from signature and digidoc4j throws NullPointerException. 

container used for testing:  
[testing.zip](https://github.com/open-eid/digidoc4j/files/1210983/testing.zip)

example code:
//container from existing file
Container container = ContainerBuilder.
                aContainer().
            fromExistingFile("testing.asice").build();
//signature from container
        Signature signature = container.getSignatures().get(0);
//trying to get certificate and DD4J throws NullPointerException
        X509Cert cert = signature.getOCSPCertificate();
        
error message in console: 
Exception in thread "main" java.lang.NullPointerException
	at org.digidoc4j.impl.bdoc.xades.TimemarkSignature.getCN(TimemarkSignature.java:125)
	at org.digidoc4j.impl.bdoc.xades.TimemarkSignature.getOCSPCommonName(TimemarkSignature.java:119)
	at org.digidoc4j.impl.bdoc.xades.TimemarkSignature.findOcspCertificate(TimemarkSignature.java:106)
	at org.digidoc4j.impl.bdoc.xades.TimemarkSignature.getOCSPCertificate(TimemarkSignature.java:56)
	at org.digidoc4j.impl.bdoc.BDocSignature.getOCSPCertificate(BDocSignature.java:80)

**Comment by isaachbn** [comment]
I went through something similar. 
That was my solution:

```java
   ASN1Primitive obj = getExtensionValue(certificate, Extension.authorityInfoAccess.getId());
   if (obj == null) {
       return null;
   } else {
       ASN1Sequence AccessDescriptions = (ASN1Sequence) obj;

       for (int i = 0; i < AccessDescriptions.size(); ++i) {
           ASN1Sequence AccessDescription = (ASN1Sequence) AccessDescriptions.getObjectAt(i);
           if (AccessDescription.size() == 2 && AccessDescription.getObjectAt(0) instanceof ASN1ObjectIdentifier) {
               ASN1ObjectIdentifier id = (ASN1ObjectIdentifier) AccessDescription.getObjectAt(0);
               if ("1.3.6.1.5.5.7.48.2".equals(id.getId())) {
                   ASN1Primitive description = (ASN1Primitive) AccessDescription.getObjectAt(1);
                   return getStringFromGeneralName(description);
               }
           }
        }
       return null;
  }
```

**My certificate is of Brazilian standard.**

**Comment by nostneji** [comment]
I investigated this issue and have a hypotesis, why it is not working. The reason for NPE is, that digidoc4j tries to find certificate by looking for OCSP name in OCSP response and then searching from list of certificates by that name. In given test container the OCSP name is missing and TimemarkSignature.getCN(x500Name) throws NPE. We can fix that part, but this will not solve the root of the problem.
OCSP response without name is not actually wrong, because the standard (https://www.ietf.org/rfc/rfc2560.txt) allows to use KeyHash instead (KeyHash ::= OCTET STRING --SHA-1 hash of responder's public key). We will look, if we can implement something which can use for lookup that keyhash value.

**Comment by nostneji** [comment]
Use of the keyhash is now supported.
