### ISSUE TITLE
DSS CommonsDataLoader is not handling not 2XX response codes properly

### ISSUE THREAD

**Issue by stanislav-degtjarjov** [open-eid/digidoc4j#57]
eu.europa.esig.dss.client.http.commons.CommonsDataLoader

function:
protected byte[] httpGet(String url);
`
httpResponse = this.getHttpResponse(client, httpRequest, url);
byte[] returnedBytes = this.readHttpResponse(url, httpResponse);
var7 = returnedBytes;
`
Basically code returns content only if the response code is 2XX, otherwise content will be null and no proper error will be thrown. Only general message will appear in the logs: "eu.europa.esig.dss.DSSException: Unable to load the LOTL: content is empty".

For instance, if the connection is blocked by proxy, the response will be 401 with message "Blocked By Web Gateway".

Proper behavior: handle all HTTP statuses. If the response code is not 2XX thow exception (3XX should be handled differently if it is the case).

**Comment by naare** [comment]
This is configurable in new DSS 5.3 version which will be included in next DD4J release.

**Comment by andresvoll** [comment]
With the merge of DSS version 5.4 the CommonsDataLoader class will throw and log the error if the response HTTP status code is not 200. The only exception is with 3XX codes, it will follow redirections only when dealing with GET and HEAD requests.
Personally I think that it's the correct behaviour, because according to the official [HTTP specification](https://tools.ietf.org/html/rfc2616#section-10.3), POST and PUT methods should not be automatically redirected as they require user confirmation.

**Comment by naare** [comment]
DD4J 3.1.0 is released.
